### ISSUE TITLE
Clarify advantages over conventional approach in documentation

### ISSUE THREAD

**Issue by alexpovel** [microsoft/vscode-python-debugger#108]
I got a really dumb question.

So I found this repo/extension from the [latest VSCode release notes](https://code.visualstudio.com/updates/v1_83#_python-debugger-updates). I guess the [extension](https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy)'s selling point is its use of `debugpy`, so I went over to [their repo](https://github.com/microsoft/debugpy) but came up short as well in search of an answer to what I was wondering about:

**What does this extension do that's not already possible?**

I don't have it installed or ever used, to my knowledge, `debugpy`, and have "always" been able to hit F5 in Python projects and have all the fabulous tools I could want available (breakpoints, conditional breakpoints, step in/out/over, step into 3rd party code, configure breaking on exceptions, debug asyncio/threads, ...). There's no feature I am missing, and also no feature I see this extension or `debugpy` has available over the conventional approach. All I have installed is [the "normal" Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python).

Is this extension a move to support the Debug Adapter Protocol? (Don't know if the Python extension uses that already) Or something else entirely? Am I missing something?

**Comment by karthiknadig** [comment]
@alexpovel The intent of this extension is to allow `debugpy` (bundled implementation) to be independent of python extension. A issue we commonly see when versions of python are deprecated (like 3.7), and python extension moves forward, people lose the ability to debug with older versions of python. They either have to pin the python extension and not receive any new capabilities of the python extension or upgrade their python environment which might not be possible. With this extension, you only get the debugger features, so you can pin it to versions that worked for you. While keeping the main python extension on latest.

Second thing that this does is platform specific builds of debugpy. In the main extension we bundle all debugpy builds for all platforms in a single extension package. This extension only bundles bits relevant to each platform, so you only get the bits that you would use.

Third, this extension implements all the same functionality as the main python extension. New features will be added here. Eventually the features in main will switch over to use this.

**Comment by alexpovel** [comment]
Thanks, appreciated!

**Comment by eikowagenknecht** [comment]
I think this should be stated in the readme. I had to search quite a while to find this issue to see what the extension is actually about.
