### ISSUE TITLE
How to make sure debugpy is used for debugging tests?

### ISSUE THREAD

**Issue by flying-sheep** [microsoft/vscode-python-debugger#112]
@brettcannon said in https://github.com/microsoft/vscode-python/issues/21748#issuecomment-1767008257 that pressing the “debug test” button in the Python extension’s test view should use this extension if available.

I tried to set the `justMyCode` setting to `true` without a launch configuration to check it out. My breakpoint in library code wasn’t respected. That makes me think that either the Python extension used its own debugger or the `justMyCode` setting doesn’t work reliably.

Is there a way to configure or even see which debugger extension provides the functionality to see which one it is?

**Comment by blakeNaccarato** [comment]
Workaround for now, as seen in referenced commit from my project template. Also possibly useful information for debugging this issue. When I introduce the adapter id `pytest` below, of type `python` (as opposed to `debugpy`), with purpose `debug-test` and `justMyCode` disabled, I can debug inside of third-party code when running test suites through the test adapter (I'm using the preview test adapter).

If the workaround `pytest` adapter just described is not present, I can't step into third-party code then running via test adapter. I've also tried setting `debug-test` purpose in the `debugpy` adapter, explicitly toggling `justMyCode` in that, using the `debugpy.debugJustMyCode` setting, and combinations of all that.

I haven't tried all of that over again while explicitly opting out of the new test adapter, however.

#### .vscode/launch.json

```JSONC
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Current file",
      "type": "debugpy",
      "request": "launch",
      "program": "${file}",
      "console": "internalConsole"
    },
    ...
    {
      "name": "pytest",
      "purpose": ["debug-test"],
      "presentation": {
        "hidden": true
      },
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "internalConsole",
      "justMyCode": false
    }
  ]
}
```

**Comment by eleanorjboyd** [comment]
@paulacamargo25, do you have any thoughts on this and if the workaround is required?

**Comment by blakeNaccarato** [comment]
I know it's just my machine, but I tried again with the latest extension version: debugging tests specifically setting the `debugpy` adapter with the `debug-test` purpose again, and with the workaround removed altogether (`debugpy.debugJustMyCode` set to `false`). It looks like for my machine that the described workaround is still required. Below are system version details from when I tried this again today. Let me know if it would help to try this with minimal extensions enabled or with extension bisect or something like that, or whether you are able to repro on your end. Thanks!

```
Python Debugger extension version: v2023.3.13271006
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by bersbersbers** [comment]
> I know it's just my machine

It's not, I have the same issue. Your workaround helps a lot. Happy to help investigate/debug this if anyone has specific instructions.

**Comment by paulacamargo25** [comment]
Since testing is handled on the python extension side, a change needs to be made to start using the python debugger extension.

**Comment by paulacamargo25** [comment]
closed in : https://github.com/microsoft/vscode-python-debugger/issues/174

**Comment by andreamah** [comment]
@paulacamargo25 do you have verification steps for this?

**Comment by bersbersbers** [comment]
This is working for me in Python Debugger v2024.2.0. Thanks!
