### ISSUE TITLE
Convert all non-string configuration properties in debug

### ISSUE THREAD

**Issue by Fedma123** [microsoft/vscode-python-debugger#115]
# Requested feature
Support port numbers in attach debug configurations as **strings** rather than numbers exclusively.
```
{
    "name": "Python: Current File",
    "type": "python",
    "request": "attach",
    "connect": {
        "host": "localhost",
        "port": "1234"
    }
```
# Motivation
The attach debug configurations expect a number as port number rather than a string. This prevents variable substitution in `launch.json`. As an example, the following configuration raises an error on the `port` key: `Incorrect type. Expected "number"`.
```
{
    "name": "Python: Current File",
    "type": "python",
    "request": "attach",
    "connect": {
        "host": "localhost",
        "port": "${env:DEFAULT_DEBUGGER_PORT}"
    },
    "console": "integratedTerminal"
}
```
# Use case
Assume that you have to debug your application by attaching to a running process. Assume that you package and debug the application into a container by attaching VSCode to the running container. Finally, assume that you have to debug parallel instances of the application on your local machine. In this scenario each debugger must use a distinct port (this is the case for containers in a podman pod at least because they share the same network). The port could be supplied as an environment variable to each container.

**Comment by brettcannon** [comment]
@int19h because all debugger stuff related to VS Code and Python should end up here. Why do you think it stay on the core extension side?

**Comment by int19h** [comment]
Sorry, I got confused about which repo it is, I thought it ended up in the core debugpy repo where it was filed originally. You're right, this is the proper tracker for it.

**Comment by andreamah** [comment]
Are there short verif steps for this feature?

**Comment by rzhao271** [comment]
I still can't specify the port as a string in a Python attach launch configuration, so it looks like the original request still isn't fixed.

![Python launch configuration indicating a type error when the port is "1234" because it's a string](https://github.com/microsoft/vscode-python-debugger/assets/7199958/de887bf9-de78-43a6-8999-5884c24044fb)

**Comment by paulacamargo25** [comment]
This issue was solved in the Python Debugger Extension.
Please use the `"type": "debugpy` for the configuration.

**Comment by rzhao271** [comment]
LGTM. Thanks!
