### ISSUE TITLE
Any plan to support older Pythons (e.g. `<=3.6`)?

### ISSUE THREAD

**Issue by dh377** [microsoft/vscode-python-debugger#123]
Our codebase is still using Python 3.6. (It's used in enterprise environments, and Python version upgrades are very conservative.) It would be better if we can designate debugpy version in config.json or can get separated extension which contains older version of `debugpy==1.5.1`.

**Comment by paulacamargo25** [comment]
Yes, just pin to the last version that starts with 2023.1.* , this version uses debugpy 1.5.1.

**Comment by dh377** [comment]
I confirmed that `2023.1.*` is working with Python 3.6. Thank you! However, there is not any sense the version is supporting Python 3.6 or `debugpy==1.5.1` in the description. I think the description should be mentioned about it.

**Comment by paulacamargo25** [comment]
Thanks @dh377, we are addressing this issue [here](https://github.com/microsoft/vscode-python-debugger/issues/121).
