### ISSUE TITLE
Provide meaningful error message (UI) when flask or django app is not configured correctly

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-python-debugger#152]
- [ ] If FLASK_APP does not point to a valid file/module, debugging/running flask fails.
We can figure this out easily and should display a to the user.
- [ ] If `manage.py` file does not exist (or path in `launch.json` is incorrect)
We can figure this out easily and should display a to the user.

**Comment by paulacamargo25** [comment]
Closing this issue since we updated the way we got the main python file for django or flask projects
