### ISSUE TITLE
Add support for debugging of python code without a file

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-python-debugger#155]
If this isn't supported to then notify the user of this.
https://github.com/Microsoft/vscode-python/issues/1940#issuecomment-397844545
https://github.com/Microsoft/vscode-python/issues/1940#issuecomment-397851330

**Comment by karthiknadig** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.
