### ISSUE TITLE
TPI: Test use Python Debugger in the core extension

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-python-debugger#181]
Refs: https://github.com/microsoft/vscode-python-debugger/issues/109

- [x] macOS @eleanorjboyd
- [x] linux @aeschli
- [x] windows @luabud

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-python-debugger/issues/new?body=Testing+%23141%0A%0A&assignees=paulacamargo25)

[Create Issue](https://github.com/microsoft/vscode-python-debugger/issues/new?body=Testing+%23181%0A%0A&assignees=paulacamargo25)

---

Prerequisites:
- Delete the current python extension

Part 1: Test extension Installation
1. Install the Python extension
2. Make sure the Python Debugger Extension has been installed

Part 2: Python extension debugger deprecated
 1. Create a launch configuration for `Python Debugger`(it doesn't matter the option)
 2. Change debug type `debugpy` to `python`.
 3. Make sure that a deprecated message is shown for `python` type
 4. Test that this configuration still works. That is, add breakpoints, and debug works for the python type.

Part 3: Test debugger configuration
1. Debug a python file using the debug view, the dynamic config, the editor button.
2. Make sure that the debugger used is the Python Debugger.
3. Check that there is no way to create. a configuration for `python` type.

**Comment by luabud** [comment]
worked as expected!

**Comment by aeschli** [comment]
works!
