### ISSUE TITLE
The Python Debugger extension does not export its API

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-python-debugger#194]
The Python Debugger extension does not export its API. This blocks the Docker extension from debugging using the new `debugpy` launch configuration. (Blocking https://github.com/microsoft/vscode-docker/issues/4221)

See https://github.com/microsoft/vscode-python-debugger/blob/1cce48cee0741f84f909e5cf897cfdaa9afa55fc/src/extension/extension.ts#L21

It returns `Promise<void>`. Compare to https://github.com/microsoft/vscode-python/blob/c0bf1b73b608d1c11b04f18966177335faea74b4/src/client/extension.ts#L61 in the current Python extension which *does* return its API.

**Comment by bwateratmsft** [comment]
The Docker extension uses the following interface:

```typescript
// Adapted from https://github.com/microsoft/vscode-python-debugger/blob/main/src/extension/api.ts
interface PythonDebuggerExtensionAPI {
    debug: {
        getDebuggerPackagePath(): Promise<string | undefined>;
    }
}
```

**Comment by paulacamargo25** [comment]
Close because is going to be solved in: https://github.com/microsoft/vscode-python-debugger/issues/194
