### ISSUE TITLE
Missing 'view value in data viewer' functionality

### ISSUE THREAD

**Issue by ArvidMartensRenson** [microsoft/vscode-python-debugger#197]
In the past when using the now deprecated "python" type debugger, we had the option to view pandas dataframes in the jupyter data viewer (if the extension is installed). We now switched to the new debugpy type debugger extension, and noticed that this functionality is not longer available. Is there any chance that this functionality will be supported in the near future?

**Comment by paulacamargo25** [comment]
Thanks for your issue report @ArvidMartensRenson, yes, for that, a change is needed in the Jupyter extension, They are already working on it, you can see this [issue](https://github.com/microsoft/vscode-jupyter/issues/15121) that refers to it.
