### ISSUE TITLE
Can't debug

### ISSUE THREAD

**Issue by Sofi2022** [microsoft/vscode-python-debugger#199]
When I push button Debug the debug window just disappears after 1 second and I don't understund why it happens. Can you resolve this problem and help me?
![py1](https://github.com/microsoft/vscode-python-debugger/assets/98352273/e1efd329-2ec9-4e45-9ee7-32f873ec80b5)
![py2](https://github.com/microsoft/vscode-python-debugger/assets/98352273/24707cc6-8ed8-44f6-a166-1ae6865d1c32)

**Comment by brettcannon** [comment]
You never actually call your `neutralize()` function, so the code doesn't run to ever hit that breakpoint. So everything is working as intended.
