### ISSUE TITLE
Can't find older version to install

### ISSUE THREAD

**Issue by bwidmeier** [microsoft/vscode-python-debugger#201]
Hi! I am interested in installing an older version of this plugin (2023.1.*), as is suggested in [this comment](https://github.com/microsoft/pylance-release/issues/5019#issuecomment-1783403189). What luabud (who I think works on this team?) describes is my situation exactly. However:
- my VSCode only lists the version that I am already on
- https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy only lists a few recent versions
- https://github.com/microsoft/vscode-python-debugger/releases only lists a single version

Is there a way to get my hands on an older version?

**Comment by paulacamargo25** [comment]
Thanks for your issue report, you can follow the steps [here](https://github.com/microsoft/vscode-python-debugger/issues/193#issuecomment-1928567891) in order to install a pre-release version of the extension.
