### ISSUE TITLE
Can't get debugger version 2023.1.* to work with Python 3.6 

### ISSUE THREAD

**Issue by bwidmeier** [microsoft/vscode-python-debugger#204]
Hi, I'm stuck on Python 3.6 for the time being. [This](https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy) and other references seem to indicate that I should be able to debug using the 2023.1.* versions of this extension. However, when I try, it isn't working for me. I can provide whatever details might be helpful. Any tips?

I am using a remote dev setup over SSH.

![image](https://github.com/microsoft/vscode-python-debugger/assets/3766063/d4be8184-4e07-4c94-9ccd-9858b09346b3)

![image](https://github.com/microsoft/vscode-python-debugger/assets/3766063/37daeddc-f615-41a3-8faf-68dd9a818e40)

![image](https://github.com/microsoft/vscode-python-debugger/assets/3766063/9be32e50-b0aa-4464-8273-ac27b84ad54b)

Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by luabud** [comment]
Hey @bwidmeier, can you make sure you have `type` set to `debugpy` in your launch.json?

E.g.:
```
       {
            "name": "Python Debugger: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
```

**Comment by bwidmeier** [comment]
Thanks so much!
