### ISSUE TITLE
Debugger Hangs When Handling Exception in Script Importing Matplotlib

### ISSUE THREAD

**Issue by jacobdwyer16** [microsoft/vscode-python-debugger#205]
### Introduction

**Background Information**: Encountered a deadlock in `vscode-python-debugger` when debugging a Python script that raises an exception after importing `matplotlib`.

**Objective**: To provide detailed information about a deadlock issue to aid in diagnosing and resolving it.

### Environment 

- Project Version: vscode-python-debugger as included in VSCode 1.86.0
- Operating System and Version: Windows 10, Version 21H2 (OS Build 22621)
- Dependencies Version: Python 3.11.4, Matplotlib 3.8.1
- Browser/Environment: VSCode Version 1.86.0 (user setup), Electron: 27.2.3, Node.js: 18.17.1

### Steps to Reproduce 

1. Initial Setup: Configure a Python project with VSCode using pyproject.toml for dependency management and a specific launch.json for debugging.

2. Action Steps:

- Include matplotlib.patches and matplotlib.pyplot in the script.
- Implement a try-except block to raise and catch a ValueError.
- Start debugging the script using the provided launch.json configuration.

*Note: I am interacting with the debugger through keyboard shortcuts.*

Script that works as expected:
```python
try:
    raise ValueError("This is a manually raised exception")
except ValueError as e:
    print("Caught exception:", str(e))
```
Script that hangs once the raised exception breakpoint is reached:
```python
import matplotlib.patches as patches
import matplotlib.pyplot as plt
from matplotlib.figure import Figure

try:
    raise ValueError("This is a manually raised exception")
except ValueError as e:
    print("Caught exception:", str(e))
```
*Note the terminal in the failing script outputs: `Backend TkAgg is interactive backend. Turning interactive mode on.`*

3. Expected Outcome: The script executes, catching and printing the exception message without any issues.

4. Actual Outcome: The debugger hangs upon raising the exception. No keyboard input is accepted or registered by VSCode, necessitating manual termination of the debug session.

### Additional Context

Configuration Files:
- launch.json: Configured for "Python Debugger: Current File" with "integratedTerminal".
- pyproject.toml: Specifies Python 3.11 and Matplotlib 3.8.1 among the project dependencies.

### Attempts to Resolve

- Troubleshooting Steps: Verified that scripts without matplotlib imports do not experience this deadlock.
- Workarounds: Currently, avoiding the import of matplotlib in scripts where exceptions are handled allows for normal debugger operation.
- Reference to Similar Issues: No similar issues found in the project's issue tracker.

### Impact 

- Severity: Moderate, impacting debugging capabilities for projects utilizing matplotlib. I can work around it my refactoring my code to work around the raised exception. 
- Urgency: Medium, as it affects developers working on data visualization projects or any project that relies on matplotlib for plotting.

**Comment by jacobdwyer16** [comment]
Adding 

```python
import matplotlib
matplotlib.use('Agg')
```
to this script avoids this behavior while keeping the original 3 imports. Not sure why this would be the case. I've run the same version of `matplotlib` for months now. This behavior began with the most recent debugger update.

**Comment by paulacamargo25** [comment]
Thanks for your bug report @jacobdwyer16. We update debugpy to its last version, maybe thats why you are getting this error now. Thanks for also commenting the solution.
