### ISSUE TITLE
How to get old vscode-python-debugger or manually build it?

### ISSUE THREAD

**Issue by lch32111** [microsoft/vscode-python-debugger#206]
Hello. 

I want to debug my python 3.6 code in vs code. So I need to install the old vscode python debugger. When I try to find an old version of python debugger, the vs code marketplace only displays 2024.0.0 version. So, I came here and checked that there is a build folder, but there is no instruction for how to build it manually.

Can I know how to get a vsix file for the old python debugger or how to build manually? (I can get the old debugger code from this repository with the older tag in the release page).

**Comment by paulacamargo25** [comment]
Thanks for your issue report, you can follow the steps [here](https://github.com/microsoft/vscode-python-debugger/issues/193#issuecomment-1928567891) in order to install a pre-release version of the extension.

**Comment by lch32111** [comment]
@paulacamargo25 Thanks. It was easy, but confused because other extensions such as vscode python could show previous versions without doing pre-release things. Anyway Thanks!
