### ISSUE TITLE
New with update today, python debugger hangs on breakpoint/silently exits early/doesn't stop when program stops

### ISSUE THREAD

**Issue by ColinBundschu** [microsoft/vscode-python-debugger#209]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Unsure if async is related, but all my code is async, so it might be. Ususally I can breakpoint in async code, and usually that code runs to completion when awaited. As of today, my well tested async code is exiting early an unpredictably. Breakpoints are getting missed that shouldn't and intermittently when I do hit a breakpoint the entire editor locks up and needs to be force stopped. If I set no breakpoints, the program exits silently at some arbitrary point in execution, skipping the call stack and returning to the command line in the output window. When this happens, the debugger keeps running. Trashcanning the console does not stop the debugger, and vscode must be killed and restarted.

## Steps to reproduce:

1. I really have no idea, sometimes my code runs fine sometimes it doesn't. Very intermittent. (The memory/CPU usage on my computer is very low during all of this)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.6
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Mysteriously, there is no output whatsoever. This whole process is completely silent.
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2024.0.1
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.67GB (102.84GB free)|
|Process Argv|--crash-reporter-id 9eaf6e24-21e5-4961-8106-73d65e55e9f2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|Memory (System)|110.05GB (105.33GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928
bg6jg535:30958357

```

</details>

**Comment by paulacamargo25** [comment]
Thanks for your bug report, could you send me your launch.json?

**Comment by paulacamargo25** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on, then we will be happy to re-open this issue to pick up where we left off.

Happy Coding!
