### ISSUE TITLE
Would it be OK to create a task to start a debugpy session and then use that task as a `preLaunchTask` in launch config

### ISSUE THREAD

**Issue by balaji** [microsoft/vscode-python-debugger#213]
## What I really want to do:
* Use remote attach to debug a python `debugpy` session
* I want this to be a single click, i.e. I don't want to run the `debugpy` session first and then click on the "Run and Debug" button.
The idea is inspired from this [blog post](https://christianheilmann.com/2022/03/17/automatically-starting-a-server-when-starting-a-debug-session-in-vs-code/)

## What I did
* In tasks.json file
```json
    {
      "label": "python debug",
      "type": "shell",
      "isBackground": true,
      "command": "${workspaceFolder}/py-start-debug",
      "presentation": {
        "reveal": "silent",
        "showReuseMessage": false,
        "clear": true,
        "close": true
      },
      "problemMatcher": [
        {
          "pattern": [
            {
              "regexp": ".",
              "file": 1,
              "line": 1,
              "column": 1,
              "message": 1
            }
          ],
          "background": {
            "activeOnStart": true,
            "beginsPattern": { "regexp": "." },
            "endsPattern": { "regexp": ".*Note: Debugging will proceed.*" }
          }
        }
      ]
    }
```

* The shell file (`py-start-debug`) - simplified:

```sh
#!/usr/bin/env bash
python -m debugpy --listen localhost:5678 --wait-for-client --log-to /tmp/debugpylogs example.py
```

* The launch.json:

```json
    {
      "name": "Python Debugger: Remote Attach",
      "type": "debugpy",
      "request": "attach",
      "connect": {
        "host": "localhost",
        "port": 5678
      },
      "preLaunchTask": "python debug",
      "pathMappings": [
        {
          "localRoot": "${workspaceFolder}",
          "remoteRoot": "."
        }
      ]
    }
```

## What happens:
The debug session works. Sometimes in the first attempt. Sometimes in the second attempt.

### Debugging working in First attempt:
![1](https://github.com/microsoft/vscode-python-debugger/assets/137302/84e6498e-c083-4b6b-b6ff-b7940016c415)

### Debugging working in Second Attempt:
![2](https://github.com/microsoft/vscode-python-debugger/assets/137302/b3035e4b-b8f9-42b1-938c-75db898dc705)

## Logs:
[First Attempt Success.zip](https://github.com/microsoft/vscode-python-debugger/files/14284165/First.Attempt.Success.zip)
[Second Attempt Success.zip](https://github.com/microsoft/vscode-python-debugger/files/14284167/Second.Attempt.Success.zip)

## Test Code:
[source.zip](https://github.com/microsoft/vscode-python-debugger/files/14284177/source.zip)

## Question:
Why would it work sometimes in the first attempt itself and why would it work only in the second attempt?

**Comment by paulacamargo25** [comment]
Thanks for your issue report, that depends on how vscode handles the attach, if the problem persists could you create an issue in the vscode repository? thank you
