### ISSUE TITLE
Additional output when running debugger compared to simply executing the file

### ISSUE THREAD

**Issue by filip-komarzyniec** [microsoft/vscode-python-debugger#219]
Hey! 

This is more of a question than a bug. The extension works great for me. I am having trouble understanding one thing though and I could not find the answer for it anywhere yet. 

Running a python file through VScode produces expected output. 
Debugging the same file, though, produces additional _SyntaxWarnings_ from a very different file in a project (completely different project tree catalogue's branch). 

What additional hooks are performed before the launch of a debugger? How can I eventually tweak them? 

I have installed whole _Python_ extension pack. 
I have no configured linters nor static code analysers like mypy. Below is my _launch.json_ config: 

<details>
<summary>laugh.json configuration</summary>

```json   
{
  "version": "0.2.0",
  "configurations": [
    
    {
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal",
      "justMyCode": false,
      "rules": [
        {"module": "my_module", "include": false},        
      ],
      "env": {
        // "PYTHONHASHSEED": "333",
      }
    }
  ]
}

```    

</details>

**Comment by paulacamargo25** [comment]
Thanks for your issue report, could you send me the error? the debugger and the running works a little  different, for the debugger we pre-processed the data. But we don't check any syntax errors.

**Comment by eleanorjboyd** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on, then we will be happy to re-open this issue to pick up where we left off.

Happy Coding!

**Comment by filip-komarzyniec** [comment]
The issue was opened so long ago that I do not really have the exact same files to reproduce it now. The codebase I was working on that time and noticed the issue has changed significantly as well. 

As I have some understanding of the original problemI'll try to provide the minimal working example (if it's even still reproducible).

**Comment by eleanorjboyd** [comment]
Hi @filip-komarzyniec, sorry for such a long time since the original issue- totally understand it is no longer reproducible in its original form. If you are able to provide a minimal working example that would be great and I really appreciate you responding after such a long time. Hopefully we can get this fixed so no other users run into it- thanks!
