### ISSUE TITLE
TPI: Open browser after launching a Django or flask app

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-python-debugger#221]
Refs: https://github.com/microsoft/vscode-python-debugger/issues/154

- [x] macOS @eleanorjboyd
- [x] linux @alexr00
- [x] windows @bamurtaugh

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-python-debugger/issues/new?body=Testing+%23221%0A%0A&assignees=paulacamargo25)

---

Prerequisites: 
1. Make sure the last pre-release version of the Python Debugger Extension has been installed.

Part 1: Test Django app
1. Open a Django Project if you already have one or you can also create one following the steps in the [Django Tutorial](https://docs.djangoproject.com/en/4.0/intro/tutorial01/).
2. Create a Django launch configuration
3. Go to your launch.json and add to the Django config: `"autoStartBrowser": true`.
4. Run the launch configuration
5. Make sure that a browser with your application running is open with the right url and port.

Part 2: Test flask app
1. Open a Flask Project if you already have one or you can also create one following the steps in the [Flask Tutorial](https://flask.palletsprojects.com/en/2.1.x/quickstart/#a-minimal-application).
2. Create a Flask launch configuration
3. Follow the same steps mention above.

Part 3: Don't open browser
1. By default this config attr is false, if the value is not in the configuration or the value is `false` no browser should be opened.

**Comment by alexr00** [comment]
Running the python debug config doesn't work:
![Uploading Recording 2024-02-20 at 12.01.52.gif…]()

**Comment by alexr00** [comment]
Looks like the Python extension is also needed.
