### ISSUE TITLE
Python Debugger should have a dependency on Python extension 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-python-debugger#222]
Testing #221

![Recording 2024-02-20 at 12 01 52](https://github.com/microsoft/vscode-python-debugger/assets/38270282/b248c7c8-0147-4167-9d4b-61a6538703cb)

It looks like the Python Debugger extension can't be used without the Python extension. One way this could be solved is by making the Python Debugger have a dependency on the Python extension. Another option would be the have a better error here.

**Comment by MrZmcH** [comment]
@alexr00 Do I need to install the "ms-python" extension here? Is there anything else?

**Comment by alexr00** [comment]
Added to the April milestone so this gets verified.
