### ISSUE TITLE
Unable to Use Python Debugging Functionality in an ARM64 Docker Environment with Code-Server

### ISSUE THREAD

**Issue by topcss** [microsoft/vscode-python-debugger#230]
Hello there,

I'm currently experiencing an issue with the Python debugging functionality in code-server running in a Docker environment on an ARM64 architecture.

**Environment Details**:
- Architecture: ARM64
- Docker Image: linuxserver/code-server
- Python Version: Python 3.10.12
- Code-Server Version: v4.21.1

**Issue Description**:
When I try to use the Python debugging functionality in code-server via a web browser interface, it doesn't work as expected.

**Steps to Reproduce**:
![image](https://github.com/microsoft/vscode-python-debugger/assets/2252451/a63392df-a70d-4760-8feb-fb1416162697)

**Expected Behavior**:
I expected to be able to use the Python debugging functionality as in a typical VS Code environment.

**Actual Behavior**:
Python debugging functionality does not work. 

I've attached screenshots to help illustrate the issue. Any assistance on this matter would be greatly appreciated. I'm eager to contribute in any way I can to help resolve this issue.

Thank you for your time and consideration.

Best Regards,
Jack

**Comment by LouisStAmour** [comment]
Likewise I'm trying to use alpine dev containers with this extension on Apple silicon and I can't.

When installing this extension, or extensions that rely on it like "Ansible", I get an error like the following: 

> Incompatible: Can't install 'ms-python.debugpy' extension because it is not compatible with the current version of Visual Studio Code (version 1.86.2).

Clicking install manually leads me to [the marketplace](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/debugpy/2024.0.0/vspackage?targetPlatform=alpine-arm64) which says: 

> Version 2024.0.0 for extension ms-python.debugpy has no support for targetPlatform alpine-arm64.

I could probably build a version of the extension manually but it would be nice to see official support. :)

**Comment by paulacamargo25** [comment]
Thanks for the issue support, we do not handle the installation process. Could you please create an issue in [vscode-remote-release](https://github.com/microsoft/vscode-remote-release).

I can check the issue with the targetPlatform. Let me investigate in order to solve it.

**Comment by rzhao271** [comment]
Hi @paulacamargo25, what are some verification steps for this issue?

@topcss let us know if the issue is resolved for you now. You may have to use the pre-release extension along with the Insiders version of Code or insiders.vscode.dev to see it. Thanks!

**Comment by rzhao271** [comment]
I successfully debugged a Python file on an Ubuntu arm64 container using the Python Debugger and Dev Container extensions.

**Comment by sevetseh28** [comment]
I'm still having this issue. Is this resolved?

**Comment by sevetseh28** [comment]
<img width="885" alt="image" src="https://github.com/microsoft/vscode-python-debugger/assets/13895313/e6a03645-e2bf-42cb-92e8-1d6a4fd5b5c5">

**Comment by sevetseh28** [comment]
Hey, adding another comment to see if I might get any updates on this ?  thank you!
