### ISSUE TITLE
how to install an extension for  python 

### ISSUE THREAD

**Issue by Anita-Nyokabi** [microsoft/vscode-python-debugger#232]

**Comment by Anita-Nyokabi** [comment]
please  help

**Comment by karthiknadig** [comment]
Thanks for the bug report, but unfortunately, we need some more information from you in order to triage this issue appropriately. Please follow instructions [here](https://aka.ms/pvsc-bug) to create a new bug with all the critical details we need for diagnosis.

**Comment by paulacamargo25** [comment]
If you want to install an extension, you can follow the steps [here](https://code.visualstudio.com/docs/editor/extension-marketplace#_browse-for-extensions).

If you need more help please create an issue explaining the problem.
