### ISSUE TITLE
Use WSL PS Error Fix

### ISSUE THREAD

**Issue by DavidArchibald** [microsoft/vscode-python-debugger#245]
The fix @JCMais contributed at microsoft/vscode-python/pull/20741 has unblocked me there but I quickly realized that it's not implemented here.

Given the code is already implemented I'd be fully capable to make a PR for this but I wanted to open an issue first in case.

**Comment by paulacamargo25** [comment]
Thanks for your initiative @DavidArchibald . Yes, feel free to create a PR in the Python Debugger extension.
