### ISSUE TITLE
It always asks to select Python interpretor when press debug button 

### ISSUE THREAD

**Issue by alexey2baranov** [microsoft/vscode-python-debugger#252]
Hi. Today vscode starts asking me to select interpretor. It doesn't see that I allready have selected one. 

I allready tryed to remove poetry environment and install it from the scratch, and remove .vscode folder and open folder from the scratch.

Please see the picture. If I press Change Python Interpretor as he asks me, then I see correctly selected one. I tried to select another one, but got the same result - it doesn't see selected interpreort. 

![image](https://github.com/microsoft/vscode-python-debugger/assets/19248996/22b042c7-a34c-453d-8af7-1825afc61017)

**Comment by paulacamargo25** [comment]
Duplicated: https://github.com/microsoft/vscode-python-debugger/issues/216
