### ISSUE TITLE
Class Information and Set a Breakpoint at All Class Methods

### ISSUE THREAD

**Issue by rheniser** [microsoft/vscode-python-debugger#254]
May we please get class information for the methods for which we set breakpoints? 

May we please get the ability to set a breakpoint at all methods in a class?

Kind regards,

Ryan

**Comment by karthiknadig** [comment]
@rheniser Unfortunately this is not supported by VS Code itself. So, we don't have a way to support this.

**Comment by karthiknadig** [comment]
> May we please get class information for the methods for which we set breakpoints?

You should be able to use the debug console to query any local or global variable when you hit the breakpoint. You should be able to get the info on the class there.
