### ISSUE TITLE
Why do I have to click two times to start debugging?

### ISSUE THREAD

**Issue by prokie** [microsoft/vscode-python-debugger#255]
This is my launch.json
```json
{
  "configurations": [
    {
      "name": "Python: Current file",
      "type": "debugpy",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal",
      "justMyCode": false
    }
  ],
  "version": "0.2.0"
}
```

I think before I could just click this button to start debugging.
![image](https://github.com/microsoft/vscode-python-debugger/assets/36114799/196b6b9b-ed43-4782-8d8e-783303bed131)

But now I also have to select here afterwards
![image](https://github.com/microsoft/vscode-python-debugger/assets/36114799/4d3f8b02-6f66-46cd-87b8-9b1e67e58a5c)

Can I configure it to just run in one step? Why is Node.js showing here?

**Comment by paulacamargo25** [comment]
Hi @prokie thats a new functionality that we implemented, you can still use the old one. Click the arrow next to the `run and debug button`, and select `Python Debugger: Debug Python File`.

<img width="342" alt="Screenshot 2024-03-07 at 2 06 07 PM" src="https://github.com/microsoft/vscode-python-debugger/assets/17892325/8865252f-bf32-47fb-8356-c50c09c8da40">

Thanks

**Comment by prokie** [comment]
But if I use `Python Debugger: Debug Python File` it does not use my `launch.json`. I need to use that one where `"justMyCode: false"`. Is there no way to configure the launch.json to be default?

**Comment by paulacamargo25** [comment]
Yes, you can add `"purpose": ["debug-in-terminal"]` to your `launch.json` config, in order to use this configuration for that button. You can see the documentation [here](https://code.visualstudio.com/docs/python/debugging#_purpose)
