### ISSUE TITLE
Debugging with pypy as the active interpreter raises RuntimeError

### ISSUE THREAD

**Issue by oddbookworm** [microsoft/vscode-python-debugger#256]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected:
When running pypy with the debugger, the only errors that occur should be from an issue with the user's code

Actual:
When debugging using pypy as the active interpreter, a RuntimeError gets raised, regardless of contents of python script being debugged.

## Steps to reproduce:

1. Set pypy as your active interpreter (I'm using PyPy3.10 from https://www.pypy.org/download.html on windows 11)
2. Try to debug any python script
3. Finish execution

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.13 (PyPy)
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Exception in thread Adapter message handler:
Traceback (most recent call last):
  File "C:\pypy\pypy3.10-v7.3.13-win64\Lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\pypy\pypy3.10-v7.3.13-win64\Lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\USER\.vscode\extensions\ms-python.python-2023.21.13261010\pythonFiles\lib\python\debugpy\launcher/../..\debugpy\common\messaging.py", line 1427, in _run_handlers        
    self._parser_thread.join()
  File "C:\pypy\pypy3.10-v7.3.13-win64\Lib\threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "C:\pypy\pypy3.10-v7.3.13-win64\Lib\threading.py", line 1117, in _wait_for_tstate_lock
    lock.release()
RuntimeError: cannot release un-acquired lock
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.21.13261010
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7700X 8-Core Processor              (16 x 4491)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.14GB (19.73GB free)|
|Process Argv|--crash-reporter-id 67a6e7f6-52dc-4a4b-9255-328ab936a95f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30880073
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30887143
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30886110
dsvsc017:30886112
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by paulacamargo25** [comment]
Thanks for your issue report, @kintonc are you using the type `python` or `debugpy` for your config?

**Comment by JamesTheAwesomeDude** [comment]
I'm getting this exact same error, too, with PyPy 3.10 7.3.15 on VS Code 1.85.2 with Python extension 2024.2.1 and Python Debugger extension 2024.0.0

```
C:\Users\…\Documents\code\test008> c: && cd c:\Users\…\Documents\code\test008 && cmd /C "c:\Users\…\Documents\code\test008\.venv\Scripts\python.exe c:\Users\…\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher 60125 -- C:\Users\…\Documents\code\test008\reg.py "
… [program output] …
Exception in thread Adapter message handler:
Traceback (most recent call last):
  File "c:\…\PyPy310\Lib\threading.py", line 1016, in _bootstrap_inner      
    self.run()
  File "c:\…\PyPy310\Lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\…\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\launcher/../..\debugpy\common\messaging.py", line 1427, in _run_handlers
    self._parser_thread.join()
  File "c:\…\PyPy310\Lib\threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "c:\…\PyPy310\Lib\threading.py", line 1117, in _wait_for_tstate_lock 
    lock.release()
RuntimeError: cannot release un-acquired lock

```

It occurs regardless of whether I use `F5` or `Ctrl+F5` to run my file.

**Comment by paulacamargo25** [comment]
I can not reproduce the issue, but we do not handle this in the python debugger extension, it is handle in debugpy. Feel free to reopen this issue https://github.com/microsoft/debugpy/issues/1198 if the error persist.
