### ISSUE TITLE
not able to run debug using vscode anymore

### ISSUE THREAD

**Issue by mrajancsr** [microsoft/vscode-python-debugger#265]
Hello, i have the following launch.json

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "cwd": "${fileDirname}",
            "env": {
                "PYTHONPATH": "${PROJ_DIR}:${PYTHONPATH}"
            }
        }
    ]
}

Operating system: Ventura 13.1
Chip: Apple M1 Max

For some reason, the debug button on top right doesn't work any more
![Screenshot 2024-03-13 at 6 26 07 PM](https://github.com/microsoft/vscode-python-debugger/assets/6164945/a507b019-ba41-4479-b29a-7540a86146bc)

And so i have to hover the mouse on the left hand side and click debug and when i do, it complains that i need to select a python interpreter and just crashes.  Its been over a month and no one has fixed this issue and its affecting my productivity.  Whats the plan on when to fix this?

**Comment by Tremirre** [comment]
same issue on my machine, changing the `type` to `debugpy` from `python` breaks the debugging with info message `Select Interpreter` followed by `Debug Stopped` crash after selecting one

**Comment by paulacamargo25** [comment]
Hi @mrajancsr thanks for your bug report, this issue has already been resolved, could you try with the latest insider version of the Python Debugger Extension? Thanks

**Comment by paulacamargo25** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on, then we will be happy to re-open this issue to pick up where we left off.

Happy Coding!
