### ISSUE TITLE
Debug using launch.json doesn't include apostrophe in string

### ISSUE THREAD

**Issue by banyula** [microsoft/vscode-python-debugger#272]
![Python-debugger-error](https://github.com/microsoft/vscode-python-debugger/assets/26210287/8fea98cd-251f-4360-8446-eafdef65a053)
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Trying to debug Python program when using option "Python Debugger: Debug using launch.json" there is an execution error (see screenshot)

## Steps to reproduce:

1. Python 3.8 installed for all users in Windows (C:\Program Files\Python38\python.exe).
2. When debugging using "Python Debugger: Debug Python file" option, the debugger starts perfectly and without errors. Executing string is:

c:; cd 'c:\Temp\FR'; & 'c:\Program Files\Python38\python.exe' 'c:\Users\mmiller\.vscode\extensions\ms-python.debugpy-2024.2.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '61954' '--' 'C:\Temp\FR\CallFlexResponse.py'
 
3. When trying to debug using "Python Debugger: Debug using launch.json" there are execution errors because strings to execute are not surrounded by single quotes, and file path contains spaces. Executing string is:

c:; cd 'c:\Temp\FR'; c:\Program Files\Python38\python.exe c:\Users\mmiller\.vscode\extensions\ms-python.debugpy-2024.2.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher 6198ndled\libs\debugpy\adapter/../..\debugpy\launcher 61984 -- C:\Temp\FR\.vscode\launch.json myarg

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
2024-03-18 20:48:48.700 [info] DAP Server launched with command: C:\Program Files\Python38\python.exe c:\Users\mmiller\.vscode\extensions\ms-python.debugpy-2024.2.0-win32-x64\bundled\libs\debugpy\adapter
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2024.2.0
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (1 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|4.00GB (0.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30992800
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470
7ghi1836:30988842

```

</details>

**Comment by paulacamargo25** [comment]
This bug will be solved [here](https://github.com/microsoft/vscode-python-debugger/issues/175).
