### ISSUE TITLE
TPI: Improve debug config selection in Django

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-python-debugger#279]
Refs: https://github.com/microsoft/vscode-python-debugger/issues/161
- [x] macOS @chrmarti
- [x] linux @aeschli 
- [x] windows @bhavyaus

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-python-debugger/issues/new?body=Testing+%23279%0A%0A&assignees=paulacamargo25)

---

Automatically detect a Django file, and show it.

### Steps

1. Open a Django Project if you already have one or you can also create one following the steps in the [Django Tutorial](https://docs.djangoproject.com/en/4.0/intro/tutorial01/).
2. Head over to the Run And Debug tab, and click on create a launch.json file.
<img width="394" alt="Screenshot 2024-03-24 at 11 31 32 AM" src="https://github.com/microsoft/vscode-python-debugger/assets/17892325/13224c8e-46b7-498d-8ef4-593d28709e41">

3. A window will open with a list of options, choose Python Debugger > Django.

### Verification

1. Valid django file
    1. Verifies that your `manage.py` file was found correctly and is displayed in the list.
    2. When you hover the item, verify that there is a button to open the file and that it works correctly.
    3. Select this option and verify that a launch.json configuration is created with the choose option.
2. Invalid django file (you can delete or change the name of the file)
    1.  Since no file was found, verify that a Default option is displayed.
    2. Select this option and verify that a launch.json configuration is created with the choose option.
3. Browse a file
   1. Click on the option `Browse Files...` and select the file that you want.
   2. Verify that a launch.json configuration is created with the choose option, and that the path has been parsed correctly.
4. Add own value
    1. You can also include your own text, type a path in the input box and press enter.
    2.  Verify that a launch.json configuration is created with the choose option.

## Notes
Django's application detection works by looking for the `manage.py`/`app.py` file in the root or in a subdirectory just one level lower. So you can try moving the manage.py file one level lower and check that it still appears.

**Comment by chrmarti** [comment]
@bhavyaus @aeschli Note that currently the extension is only published for a subset of platforms (#282). You can download the latest for testing from the latest (red) build for the main branch at https://dev.azure.com/monacotools/Monaco/_build?definitionId=499.
