### ISSUE TITLE
Launch config suggests `manage.py` as the default despite no such file in workspace.

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode-python-debugger#281]
Testing #279

Found when verifying the below steps from the issue mentioned ^

> Invalid django file (you can delete or change the name of the file)
> Since no file was found, verify that a Default option is displayed.
> Select this option and verify that a launch.json configuration is created with the choose option.

**Comment by paulacamargo25** [comment]
That was the default behavior, so we decided to keep it.
