### ISSUE TITLE
Django debug config selection: Manually entering the path does not work

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-python-debugger#284]
Testing #279

- create a new launch config: Python Debugger > Django
- In the dialog do not select a suggested option, but enter `${workspaceFolder}/moooo.py`. That location does not exist (yet).
- Press Enter

The created launch config references `"program": "${workspaceFolder}/manage.py"`, not `moooo.py`

**Comment by paulacamargo25** [comment]
Duplicated: https://github.com/microsoft/vscode-python-debugger/issues/283
