### ISSUE TITLE
os.environ misses my variable in the debugger

### ISSUE THREAD

**Issue by duaneellissd** [microsoft/vscode-python-debugger#293]
I have a windows batch file, it does the following:

a) step 1: creates an ENV variable - ie, the statement:  set FOOBAR=12345678
 WINDOWS does not use an export statement like LINUX uses.
 so My thinking {which is probably wrong) is that it should be in the environment.

b) step 2 - Launches VS CODE
My "FOOBAR" variable should be present - I would think

c) Run python and example: "os.environ" - ie Print the environment.

QUESTION: What happened to my variable: "FOOBAR"

**Comment by karthiknadig** [comment]
@duaneellissd Are you setting this and then launching VS Code from that terminal or are you using this in debug configuration?

If you are using the terminal method then this is what you should be doing:
* Exit all VS Code instances
* Open a terminal outside of VS Code and `cd` to your project directory.
*  Run `set  FOOBAR=12345678`
* Launch VS Code from that terminal using `code .`

You can verify this from inside VS Code by opening any terminal and running `set FOOBAR`.

![image](https://github.com/microsoft/vscode-python-debugger/assets/3840081/d5d05c67-8db1-461b-98f8-cb28471a615d)

Running in terminal:
![image](https://github.com/microsoft/vscode-python-debugger/assets/3840081/83304581-6cfc-406b-ad54-74c989e0a6d6)

Running via debugger:
![image](https://github.com/microsoft/vscode-python-debugger/assets/3840081/35c80e6e-9929-4713-9cf3-4361f23d0e31)

**Comment by paulacamargo25** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on, then we will be happy to re-open this issue to pick up where we left off.

Happy Coding!
