### ISSUE TITLE
v2024.0.1 - VSCode Debug "Couldn't find a debug adapter descriptor for debug type 'debugpy'"

### ISSUE THREAD

**Issue by RyanHCCSI** [microsoft/vscode-python-debugger#297]
Environment

- VSCode 1.87.2
- Python Debugger v2024.2.0

Issue
When running a debugpy debug session, the following error message shows:
![debug_adaptor_dialog](https://github.com/microsoft/vscode-python-debugger/assets/27027152/508096df-bb3d-4fde-b8b8-9e38538e3a46)
"Couldn't find a debug adapter descriptor for debug type 'debugpy' (extension might have failed to activate)

Resolution

- Install previous version 2024.0.1

**Comment by RyanHCCSI** [comment]
I was wrong, I think the issue is with something environment specific.

**Comment by xlnn** [comment]
Try reinstalling your extension. This is a known error.

**Comment by edervishaj** [comment]
I tried reinstalling the extension, and then VSCode. Nothing worked.
