### ISSUE TITLE
TPI: Test representation change of debug variables, base 16

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-python-debugger#323]
Refs: https://github.com/microsoft/vscode-python-debugger/issues/215

- [x] macOS @eleanorjboyd
- [x] linux @aeschli
- [x] windows @bamurtaugh

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode-python-debugger/issues/new?body=Testing+%23323%0A%0A&assignees=paulacamargo25)

---

# Requirements:
1. Latest VS Code insiders
2. Latest Python Extension insiders (pre-release)
3. Latest Python Debugger Extension  insiders (pre-release)

# Verification steps
1. Create a simple python file with int or float variables.
2. Add some breakpoints in the variables.
4. Run the debugger, and open the debug Variables View.
5. You will see an `eye icon` next to the numbers variables.
6. Click it, and make sure that the value changed to its hex value.
7. Verify that you can also go back to the base 10 representation.

1. Create a simple Python file with int or float variables.
2. Add some breakpoints on variables.
4. Run the debugger and open the Debug Variables View.
5. You will see an `eye icon` next to the numeric variables.
6. Click on it and make sure the value has changed to its hexadecimal value.
7. Verify that you can also return to base 10 representation.

**Comment by aeschli** [comment]
I don't see the eye icon. Created https://github.com/microsoft/vscode-python-debugger/issues/324

**Comment by bamurtaugh** [comment]
It looks like all 3 of us are blocked on https://github.com/microsoft/vscode-python-debugger/issues/324. I'll tentatively unassign myself too and close the issue, but please feel free to reopen and reassign me if I've missed something!
