### ISSUE TITLE
Unable to  install pre-release verion extension of python debugger

### ISSUE THREAD

**Issue by Arielqjl** [microsoft/vscode-python-debugger#339]
I'm working on a project that's locked in the past. I'm trying to install a 2023.1.xxx version, but am seeing no way to do so. There's no entrance.
![Uploading 001.jpg…]()

**Comment by Arielqjl** [comment]
![image](https://github.com/microsoft/vscode-python-debugger/assets/31853775/db2cc9a8-f5d0-4621-82f9-c764f849d531)

**Comment by vsurjeet** [comment]
did not download python debugger in vs coder

**Comment by paulacamargo25** [comment]
Thanks for your issue report,, could you try the steps [here](https://github.com/microsoft/vscode-python-debugger/issues/193#issuecomment-1928567891)? Thank you

**Comment by paulacamargo25** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on, then we will be happy to re-open this issue to pick up where we left off.

Happy Coding!
