### ISSUE TITLE
Breakpoints on justMyCode: false not working properply in 1.90.0

### ISSUE THREAD

**Issue by michuhu** [microsoft/vscode-python-debugger#356]
Type: <b>Bug</b>

# Behaviour

Breakpoints on justMyCode: false not working properply in 1.90.0

Also submitted [on vscode main github issues](https://github.com/microsoft/vscode/issues/214451) since I don't know where the error occurs. Someone else also posted this issue on main vscode GH, but with no details (link on the page).

## Steps to reproduce:

1. VSCode version 1.90.0
2. `"justMyCode": false`,
3. set breakpoint anywhere in outside of your code.
4. hit run - the breakpoint will highlight somewhere in your code, the breakpoint outside of your code will be in green and steps will not move the selection forward (the app will proceed however). With each step, vscode will come back to some line or breakpoint in your code.

Works in version 1.89.1

# Diagnostic data
<details>

<summary><code>launch.json</code> configuration
</summary>

<p>

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "chat.py",
            "type": "debugpy",
            "request": "launch",
            "program": "${workspaceFolder}/chat.py",
            "console": "integratedTerminal",
            "justMyCode": false,
        },
        {
            "name": "uvicorn local",
            "type": "debugpy",
            "request": "launch",
            "env": {
                "OBJC_DISABLE_INITIALIZE_FORK_SAFETY": "YES"
            },
            "module": "uvicorn",
            "args": [
                "app:app",
                "--reload",
            ],
            "justMyCode": false,
        },
    ]
}
```

</p>
</details>

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
nothing
```

</p>
</details>

<details>

<summary>Output for <code>Python Debugger</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python Debugger</code>)
</summary>

<p>

```
2024-06-06 14:59:31.112 [info] DAP Server launched with command: .../.venv/bin/python .../.vscode/extensions/ms-python.debugpy-2024.6.0-darwin-arm64/bundled/libs/debugpy/adapter
2024-06-06 14:59:32.141 [info] Connecting to DAP Server at:  127.0.0.1:59701
2024-06-06 14:59:32.167 [info] Connecting to DAP Server at:  127.0.0.1:59701

```

</p>
</details>

Extension version: 2024.6.0
VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:34:48.028Z)
OS version: Darwin arm64 23.5.0
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.13
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): VirtualEnvironment<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id cf0a53ce-7464-4c78-875e-81033be10546|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by MRogelio** [comment]
Apparently it's caused by the Python extension
https://github.com/microsoft/vscode/issues/214433#issuecomment-2152262171

**Comment by devymex** [comment]
Same issue

**Comment by geppi** [comment]
+1

**Comment by geppi** [comment]
Rolling back to 1.89.1 resolves the issue.

**Comment by saiyuhang123** [comment]
+1

**Comment by uvnikgupta** [comment]
> Rolling back to 1.89.1 resolves the issue.

How to roll back to 1.89.1? I do not see this option in available versions

**Comment by uvnikgupta** [comment]
For those who are still wondering (as I was just a few minutes ago), you can download v1.89 from [here](https://code.visualstudio.com/updates/v1_89)

**Comment by rchiodo** [comment]
This should be a problem in VS code. See this issue:
https://github.com/microsoft/vscode/issues/214433
