### ISSUE TITLE
Debugging Broken (F10 & F11)

### ISSUE THREAD

**Issue by fierval** [microsoft/vscode-python-debugger#358]
Type: <b>Bug</b>

# Behaviour
When Hitting F11 and sometimes F10, the debugger breakpoint indicator is blinking and not stepping in or over the line. F5 works

## Steps to reproduce:

1. Put a breakpoint on a function
2. Start debugging and F5 to the breakpoint
3. F11 to step into the function

Result: keep hitting F11, the indicator just blinks, nothing happens.

Not repro on 1.89.1

# Diagnostic data
<details>

<summary><code>launch.json</code> configuration
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>Output for <code>Python Debugger</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python Debugger</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Extension version: 2024.6.0
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22621
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.13
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor             (32 x 4491)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.14GB (102.74GB free)|
|Process Argv|--crash-reporter-id ebad9e78-b813-4680-b34a-3acad8c2e7ed|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
2f103344:31067618
26j00206:31048877

```

</details>

**Comment by fierval** [comment]
Additionally, setting `just my code` to false has no effect. Can't step into the package code.

https://github.com/microsoft/vscode-python-debugger/assets/987574/30442564-fbe3-4b9a-9c5e-33ac4d7285a3

**Comment by devymex** [comment]
Same issue: https://github.com/microsoft/vscode-python-debugger/issues/359

**Comment by fierval** [comment]
This doesn't just affect a 3rd party library. Stepping into a function in "my" code is also sometimes broken, e.g.: when trying to step into a function overridden in the derived class from a parent class.

**Comment by paulacamargo25** [comment]
There was a known issue in vscode https://github.com/microsoft/vscode/issues/214433. It's marked as a candidate so it should ship soon.

**Comment by paulacamargo25** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on, then we will be happy to re-open this issue to pick up where we left off.

Happy Coding!
