### ISSUE TITLE
Single-stepping through third-party libraries during debugging is not possible

### ISSUE THREAD

**Issue by devymex** [microsoft/vscode-python-debugger#359]
Type: <b>Bug</b>

# Behaviour

When justmycode is enabled, When justmycode is enabled, single-stepping through third-party libraries during debugging is not possible.

When I press F11 from my program to step into a third-party library, the current cursor indicator (yellow arrow) remains pointing to the call line in my program. A green arrow appears next to the actual current line in the called position within the third-party library. At this point, the CALL STACK window still shows the current module as being in my program. Even if I click on the third-party library module (which is at the top of the stack), I cannot 'activate' the current line in the third-party library module (the green arrow does not turn yellow). This issue prevents me from continuously stepping through the third-party library code with F10, forcing me to switch back and forth between my files and the third-party library code files, significantly impacting development efficiency.

## Steps to reproduce:

1.  My `launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "debugpy",
            "type": "debugpy",
            "request": "launch",
            "program": "test.py",
            "console": "integratedTerminal",
            "cwd": "${workspaceFolder}",
            "env": {
                "PYTHONPATH": "${cwd}"
            },
            "justMyCode": false
        }
    ]
}
```

My code:

```python
import numpy as np
from PIL import Image

img = Image.open('test.jpg')
print(img)

```

![bug](https://github.com/microsoft/vscode-python-debugger/assets/1797836/e482446b-2e3a-4d04-96c1-ce3fa788e189)

Extension version: 2024.6.0
VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:43:07.605Z)
OS version: Linux x64 5.19.0-41-generic
Modes:
Remote OS version: Linux x64 5.4.119-19.0009.28

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.9
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): VirtualEnvironment<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.06GB (24.93GB free)|
|Process Argv|--crash-reporter-id 681870e4-3d75-4e81-a92c-21878a28d682|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: h800-tc-39|
|OS|Linux x64 5.4.119-19.0009.28|
|CPUs|Intel(R) Xeon(R) Platinum 8480+ (200 x 0)|
|Memory (System)|1877.99GB (1710.75GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideoc:31016891
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
2f103344:31067618
26j00206:31048877

```

</details>

**Comment by simone-viozzi** [comment]
Same issue here,
is there a workaround?

**Comment by BrunoCoimbra** [comment]
Is it the same as #357?

**Comment by devymex** [comment]
> Is it the same as #357?

Yes

**Comment by paulacamargo25** [comment]
Issue solved in https://github.com/microsoft/vscode/issues/214433.
