### ISSUE TITLE
Frame skipped from debugging during step-in.

### ISSUE THREAD

**Issue by jinec** [microsoft/vscode-python-debugger#360]
Type: <b>Bug</b>

# Behaviour
        {
            "name": "Python 调试程序2",
            "type": "debugpy",
            "request": "launch",
            "program": "l2_dpo2sft_json.py",
            "console": "integratedTerminal",
            "justMyCode": false,
            "purpose": ["debug-in-terminal"]
        },
XXX

step into(F11)不起作用

**Comment by paulacamargo25** [comment]
Closed in: https://github.com/microsoft/vscode/issues/214433.
