### ISSUE TITLE
Frame Skipped from Debugging Even after setting justMyCode to false, tried cleaning cache and rewritting script.

### ISSUE THREAD

**Issue by gurwinderintel** [microsoft/vscode-python-debugger#365]
Type: <b>Bug</b>

# Behaviour

Frame Skipped from Debugging Even after setting justMyCode to false, tried cleaning cache and rewritting script.

## Steps to reproduce:

1. launch.json

 {
            "name": "Python Debugger: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false
        }

# Diagnostic data
<details>
Frame skipped from debugging during step-in.
<summary><code>launch.json</code> configuration
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Extension version: 2024.6.0
VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-88-generic

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.14
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (2.54GB free)|
|Process Argv|--crash-reporter-id b59f19bc-a601-46ad-835c-98616f2a8243|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.75.194.111|
|OS|Linux x64 5.15.0-88-generic|
|CPUs|Intel(R) Xeon(R) Platinum 8352Y CPU @ 2.20GHz (128 x 800)|
|Memory (System)|251.33GB (246.36GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
2f103344:31071589
26j00206:31048877

```

</details>

**Comment by paulacamargo25** [comment]
solved in: https://github.com/microsoft/vscode/issues/214433
