### ISSUE TITLE
cant start debugging

### ISSUE THREAD

**Issue by utkarsh-utkarsh** [microsoft/vscode-python-debugger#366]
Type: <b>Bug</b>

when i start debugging it doesnt work even after installing extension

Extension version: 2024.8.1
VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:01:24.262Z)
OS version: Windows_NT x64 10.0.22631
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Default

<details>
<summary>User Settings</summary>
<p>

```

languageServer: "Jedi"

```
</p>
</details>

<details>
<summary>Installed Extensions</summary>

|Extension Name|Extension Id|Version|
|---|---|---|
|JavaScript Debugger|ms-vscode.js-debug|1.90.0|
|JavaScript Debugger Companion Extension|ms-vscode.js-debug-companion|1.1.2|
|Pylance|ms-python.vscode-pylance|2024.6.1|
|Python|ms-python.python|2024.8.1|
|Python Debugger|ms-python.debugpy|2024.6.0|
|Table Visualizer for JavaScript Profiles|ms-vscode.vscode-js-profile-table|1.0.9|
|VSCode Terminal For Ubuntu|Docter60.vscode-terminal-for-ubuntu|0.0.2|
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (3.24GB free)|
|Process Argv|--crash-reporter-id ace67d93-3c22-42a0-b505-487ede67908e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870

```

</details>

**Comment by mscreations** [comment]
Try adding to your launch.json:

"justMyCode": false

This worked for me with Python 3.12.4, extension v2024.6.0 and vscode 1.90.1 (latest versions allowed by my org)

It seems to me like this particular feature is broken with the python debugger.

**Comment by paulacamargo25** [comment]
Thanks for your bug report, could you send me your launch.json config, and how are you starting the debugger? thanks

**Comment by eleanorjboyd** [comment]
closing, please comment and we can reopen if this is still an issue! Thanks
