### ISSUE TITLE
issue. closing processes with concurrent.futures.ProcessPoolExecutor using python==3.11 and debug configuraiton

### ISSUE THREAD

**Issue by achenry** [microsoft/vscode-python-debugger#369]
works from command line and with python==3.12

**Comment by karthiknadig** [comment]
Thanks for the bug report, but unfortunately, we need some more information from you in order to triage this issue appropriately. Please follow instructions [here](https://aka.ms/pvsc-bug) to create a new bug with all the critical details we need for diagnosis.
