### ISSUE TITLE
Unexpected inline values

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-python-debugger#400]
Testing #396

Just noticing some values that don't seem helpful to annotate inline. Not sure whether it's expected or not.

The import statement

![Image](https://github.com/user-attachments/assets/80059649-d784-4b0c-8dc5-079c9afaf4c2)

The `pop` method

![Image](https://github.com/user-attachments/assets/1b2ac5d9-a585-48ff-9e2b-9141c632981e)

**Comment by roblourens** [comment]
`x` is a global variable, and also a class member and an argument for the lambda, but those are annotated with the global value
This also shows the `Cls` value which doesn't seem helpful

![Image](https://github.com/user-attachments/assets/180e00c0-2511-420a-95d8-4ccc586038d7)

**Comment by roblourens** [comment]
Just another example of showing a method as an inline value, I think that will be very noisy in typical python code



![Image](https://github.com/user-attachments/assets/2e19920f-adf4-420c-b3f8-91bd82adffec)

**Comment by luabud** [comment]
@paulacamargo25 @karthiknadig we should probably make inline values disabled by default for now? I think we need to figure out the criteria for showing these inline values, or potentially format them differently

**Comment by paulacamargo25** [comment]
Almost all the bugs here will be resolved in https://github.com/microsoft/vscode-python-debugger/pull/409.

https://github.com/microsoft/vscode-python-debugger/issues/400#issuecomment-2245936587 this one seems to be a bug in vscode, i wll create an issue.

**Comment by DonJayamanne** [comment]
> we should probably make inline values disabled by default for now? I think we need to figure out the criteria for showing these inline values, or potentially format them differently

I agree, I just debugged some of my Python code, and there were way too many inline values, to the point i looked for a way to turn it off completely.

**Comment by paulacamargo25** [comment]
To verify this, set showPythonInlineValues to true.
