### ISSUE TITLE
Setting to turn off/on Inline Values?

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-python-debugger#402]
Testing #396

Do we need a setting that controls whether or not Inline Values are displayed while debugging?

**Comment by paulacamargo25** [comment]
Yes, there is already a setting for Inline values. The default value is auto, but you can also turn it off.
![Screenshot 2024-07-23 at 5 39 37 PM](https://github.com/user-attachments/assets/4e37f6a7-4261-4ebb-938c-3b3aadeca712)

**Comment by chrisdias** [comment]
sorry I missed that setting, I was looking under `Python.` and didn't even think of looking under `Debug` 🤦
