### ISSUE TITLE
Wrong marker on literal string with same name as variable

### ISSUE THREAD

**Issue by yajo** [microsoft/vscode-python-debugger#408]
Type: <b>Bug</b>

# Behaviour

![image](https://github.com/user-attachments/assets/39473170-93fc-431f-98a5-32fa755917c9)

## Steps to reproduce:

1. Debug some code where a literal string has the same name as a variable.

# Diagnostic data
<details>

<summary><code>launch.json</code> configuration
</summary>

<p>

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Run selected test",
      "type": "python",
      "request": "launch",
      "console": "internalConsole",
      "internalConsoleOptions": "openOnFirstSessionStart",
      "justMyCode": false,
      "subProcess": true,
      "preLaunchTask": "Dependency services",
      "program": "${env:PRJ_DATA_DIR}/venv/odoo-${env:ODOO_VERSION}/bin/odoo",
      "args": [
        "--dev=qweb,xml",
        "--stop-after-init",
        "--workers=0",
        "--test-file=${file}",
        "--test-tags=.${selectedText}"
      ]
    }
  ]
}
```

</p>
</details>

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

[python.log](https://github.com/user-attachments/files/16372557/python.log)

</details>

<details>

<summary>Output for <code>Python Debugger</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python Debugger</code>)
</summary>

<p>

```
2024-07-25 07:25:32.772 [info] Name: Python Debugger
2024-07-25 07:25:32.772 [info] Module: debugpy
2024-07-25 07:56:42.853 [info] Name: Python Debugger
2024-07-25 07:56:42.853 [info] Module: debugpy
2024-07-25 08:21:01.479 [info] Name: Python Debugger
2024-07-25 08:21:01.479 [info] Module: debugpy
2024-07-25 08:27:34.056 [info] Name: Python Debugger
2024-07-25 08:27:34.056 [info] Module: debugpy
2024-07-25 08:37:19.497 [info] Name: Python Debugger
2024-07-25 08:37:19.497 [info] Module: debugpy
```

</p>
</details>

Extension version: 2024.9.12041012
VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:41.959Z)
OS version: Linux x64 6.6.41
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.14
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): VirtualEnvironment<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1360P (16 x 1683)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|15.29GB (9.46GB free)|
|Process Argv|--crash-reporter-id b63bfa16-331f-4806-adea-efa40e7321e8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31101459
ccplt:31103426
pythonrstrctxtcf:31103194

```

</details>

**Comment by paulacamargo25** [comment]
Duplicated of: https://github.com/microsoft/vscode-python-debugger/issues/401
