### ISSUE TITLE
Error on "esc" in process dropdown

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-python-debugger#41]
while testing: https://github.com/microsoft/vscode-python-debugger/issues/35

1. add configuration on debug and run panel
2. select "debugpy" and make a "debug with process ID"
3. select this config then click run
4. when the dropdown pops up that prompts you to pick a process, press the "esc" key
5. the following error message pops up

<img width="1717" alt="Screenshot 2023-06-27 at 1 48 49 PM" src="https://github.com/microsoft/vscode-python-debugger/assets/26030610/eed3a9ef-cbeb-438e-af84-3d2378dd5a4c">

**Comment by paulacamargo25** [comment]
Duplicated of https://github.com/microsoft/vscode-python-debugger/issues/38
