### ISSUE TITLE
Pytest. Rerun code in debug ignores launch.json config

### ISSUE THREAD

**Issue by slavanorm** [microsoft/vscode-python-debugger#418]
Hello. Thanks for your work. 

I experienced this bug when i had some customization for "debug tests" configuration in launch.json file.
Debug works, using customized cwd in launch.json, while it fails not finding cwd related imports when I click rerun. 

After looking into project configuration, I should apologize in advance if this issue doesnt belong here, 
as my launch.json uses type:python instead of recommended type:debugpy.
unfortunately, the same code is not capable to debug with debugpy at all.
maybe it requires different issue created?
 
Project organization:
root/
    pyproject.toml (this should configure rootdir for pytest. it fails on rerun.)
    src/
...
    tests/
...

launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Streamlit debug",
            "type": "python",
            "request": "launch",
            "module": "streamlit",
            "args": [
                "run",
                "${workspaceFolder}/src/main.py"
            ],
            "justMyCode": true,
            "console": "internalConsole",
            "envFile": "${workspaceFolder}/.env"
        },
        {
            "name": "Debug test file",
            "type": "python",
            "request": "launch",
            "console": "internalConsole",
            "purpose": [
                "debug-test"
            ],
            "env": {
                "_PYTEST_RAISE": "1",
                "PYTEST_ADDOPTS": "--no-cov"
            },
            "program": "${file}",
            "justMyCode": true,
        },
    ]
}
```
versions:
python debugger extension: v2024.6.0
pytest:8.2.0
vscode:
Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045
WSL on Win10

**Comment by paulacamargo25** [comment]
Thanks @slavanorm for your bug report, there is a know error for the reload behaviour in tests [here](https://github.com/microsoft/vscode-python/issues/19030). What I can help you with is to see the error when using `type: debugpy`. Can you share your Python Debugger Output Logs or the error that you are getting?

**Comment by slavanorm** [comment]
I couldn't manage to make tests work with debugpy at all. 
Is it possible?

**Comment by paulacamargo25** [comment]
Yes, it should work for testing, Can you share your Python Debugger Output Logs or the error that you are getting?

**Comment by slavanorm** [comment]
unfortunately i dont have access to that code anymore.

i guess, this bug is already documented, right? we can close this issue then?

**Comment by slavanorm** [comment]
The most important part of this issue is documented in another one. This is closed as duplicate
