### ISSUE TITLE
DatasetError computing data from repository

### ISSUE THREAD

**Issue by Charlesokpalactr** [microsoft/vscode-python-debugger#436]
DatasetError computing data from repository in updated VS Code.
![Capture2](https://github.com/user-attachments/assets/e2876125-2ee8-45ff-a9fb-00c7272a6f6d)
![Capture](https://github.com/user-attachments/assets/e666ddf9-e0da-478d-b228-1f7b2606a8cb)

**Comment by karthiknadig** [comment]
@Charlesokpalactr I don't think this is an issue with the debugger or the extension. It seems like the import isn't defined properly for the class.
