### ISSUE TITLE
The 'Python Debugger' extension is not available in VSCodium for Mac.

### ISSUE THREAD

**Issue by elixirbeats** [microsoft/vscode-python-debugger#438]
As the title states, this extension does not work for vs codium on a macbook pro intel. I've searched around and not found other issues mentioning this..

**Comment by karthiknadig** [comment]
You should file an issue on https://github.com/open-vsx/publish-extensions/issues . We publish extension only to the Microsoft VS Code marketplace. The build scripts and the process is all available in this repo and main python extension is published in a similar manner.
