### ISSUE TITLE
Python debugger VS Code debugger presents variable values next to the code

### ISSUE THREAD

**Issue by TamerGezici** [microsoft/vscode-python-debugger#442]
Hi,

After updating VS Code to the latest version, in debugger I'm seeing the values of corresponding code or variables like this (parts highlighted in orange-ish):

![image](https://github.com/user-attachments/assets/88635138-6c0f-40da-b161-447a997550e8)

Is this a bug? How can I disable these?

**Comment by TamerGezici** [comment]
I think I was using some preview version of a few plugins which caused this weird behaviour. When I rolled back it was fixed.

**Comment by GentilsTo** [comment]
This is an expected feature "Inline variable values in source code" with :    `debugpy.showPythonInlineValues = True` , as detailed in the 1.92.2 release note.

**Comment by TamerGezici** [comment]
@GentilsTo 

Thanks!
