### ISSUE TITLE
debugpy launch-with-arguments: there can be only one

### ISSUE THREAD

**Issue by dmaziuk** [microsoft/vscode-python-debugger#465]
Version: 1.93.1
OS: Windows 11

Similar to #233 only different: when passing more than a single command line arg via "Command Line Arguments" prompt, the whole string is wrapped in quotes and passed as a single arg. E.g. passing "-v" works, passing "-l logfile.log" breaks `argparse` or anything that expects those in separate elements in `sys.argv`

**Comment by eleanorjboyd** [comment]
yes understood this seems to be an ongoing issue. In the meantime does doing "-l=logfile.log" help at all? Or no given you are attempting multiple arguments?

**Comment by dmaziuk** [comment]
I usually need multiple arguments, yes.

It also won't work with combinations of switches e.g. `-a -b` and/or positional args `one two three` etc.

**Comment by karthiknadig** [comment]
The `"${command:pickArgs}"` is actually implemented in VS Code. This should be fixed there.

Duplicate of: https://github.com/microsoft/vscode/issues/232560
