### ISSUE TITLE
Support Python 3.13

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode-python-debugger#476]
Python 3.13 has been released more than a week ago. https://github.com/microsoft/debugpy/releases/tag/v1.8.7 has added required fixes to support Python 3.13, compare https://github.com/microsoft/debugpy/issues/1689. Since this extension bundles debugpy, a new release may be required.

**Comment by karthiknadig** [comment]
The support is already available in pre-release try v2024.11.2024101102

**Comment by karthiknadig** [comment]
We will publish a stable soon.
