### ISSUE TITLE
Version 2024.12.0 gives this error: ImportError: cannot import name 'Literal' from 'typing'

### ISSUE THREAD

**Issue by SaulBurgos** [microsoft/vscode-python-debugger#482]
Today my vs code extension was updated automatically and I got this error. 

Sadly I am working on a legacy system that needs: python 3.7.16. 

# Error 
![Image](https://github.com/user-attachments/assets/f7def37a-2657-4929-bc31-b2ed0094f910)

# Update that gave me the error 
![Image](https://github.com/user-attachments/assets/8af94746-f750-4aef-b935-c99e23d2e77a)

# Solution 
My solution was to go back to the previous version 2024.10.0 
![Image](https://github.com/user-attachments/assets/4aace400-5d3f-45f5-9bae-5a7d593aa6e1)

**Comment by karthiknadig** [comment]
@SaulBurgos You can pin the debugger to an older version that supports 3.7. That would be (2024.0.* for the Python Debugger extension)

You can see here for more details: https://github.com/microsoft/vscode-python-debugger?tab=readme-ov-file#limited-support-for-deprecated-python-versions
