### ISSUE TITLE
The lasted version 2024.12.0 can't work for python3.7

### ISSUE THREAD

**Issue by HarukazeW** [microsoft/vscode-python-debugger#486]
It looks like the file ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_plugin_utils.py uses the Literal feature, which is not supported in Python 3.7.

The documentation states: This extension is supported for all [actively supported versions](https://devguide.python.org/#status-of-python-branches) of the Python language (i.e., Python >= 3.7).

**Comment by karthiknadig** [comment]
This is by design, python 3.7 has been deprecated for nearly a year. See this table for compatibility:
https://github.com/microsoft/vscode-python-debugger?tab=readme-ov-file#limited-support-for-deprecated-python-versions
