### ISSUE TITLE
Python Debugger Extension v2024.12.0 failed adapting VSCode 1.94.2(user setup)

### ISSUE THREAD

**Issue by Vincent339** [microsoft/vscode-python-debugger#487]
OS: Windows 11.
VSCode: 1.94.2(user setup) latest
Conda: 24.7.1 
Python: 3.12.4
Python Extension: v2024.16.1
Python Debugger Extension: v2024.12.0

Failed to load Python Interpreter in the Extension framewok. Console run/debug directly works well. But GUI won't respond anyway. 

Since the extension using is such simple procedure,  I reckon it's version mismatch issue.

Please provide a workable latest version combination of above tools on Windows 11. 

Highly appreciated.

**Comment by eleanorjboyd** [comment]
Hi! Could you include a video of what is happening? When you say `Failed to load Python Interpreter in the Extension framewok` does nothing python related work in the UI / extension? What errors are you getting / seeing as you try to run from the UI

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on then we will be happy to re-open this issue to pick up where we left off.
