### ISSUE TITLE
Debugger stopped working - runs raw path to python with error

### ISSUE THREAD

**Issue by DimitryNechaev** [microsoft/vscode-python-debugger#494]
Out of nowhere can't debug any of my projects

c:\Program: The term 'c:\Program' is not recognized as a name of a cmdlet, function, script file, or executable program.

![Image](https://github.com/user-attachments/assets/5c54c9c5-1c4b-49a4-ab83-788bd514cae6)

Changing "Python: Select Interpreter path" 
![Image](https://github.com/user-attachments/assets/5ea96c8e-e930-48d0-af19-231b7c290170)

Or in settings:
![Image](https://github.com/user-attachments/assets/d464c685-5e9f-4c9f-82d3-093f168da7c7)

Has absolutely no effect on the path to Python in the debugger. It has no means of control.

**Comment by eleanorjboyd** [comment]
@Tyriar any thoughts here? Seems to be selecting the wrong shell prompt and causing an error but i am not super familiar with this section of the code so Im not totally sure.

**Comment by DimitryNechaev** [comment]
I narrowed this down to using parameters. Without parameters it runs correct command.

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "ProcessOrders",
            "type": "debugpy",
            "request": "launch",
            "program": "ProcessOrders.py",
            "console": "integratedTerminal"
        },
        {
            "name": "TestMarlinOrder <99699>",
            "type": "debugpy",
            "request": "launch",
            "program": "TestMarlinOrder.py",
            "args": "99699",
            "console": "integratedTerminal"
        },        
        {
            "name": "TestMarlinOrder <param>",
            "type": "debugpy",
            "request": "launch",
            "program": "TestMarlinOrder.py",
            "args": "${input:orderid}",
            "console": "integratedTerminal"
        },
    ],
    "inputs": [
        {
            "id": "orderid",
            "type": "promptString",
            "description": "Order ID",
            "default": "99698"
        }
    ]
}
```

without parameter:
```
PS C:\work\Test>  c:; cd 'c:\work\Test'; & 'c:\Program Files\Python312\python.exe' 'c:\Users\<me>\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '54574' '--' 'ProcessOrders.py'
```
Runs OK.

with parameter:
```
PS C:\work\Test>  c:; cd 'c:\work\Test'; c:\Program Files\Python312\python.exe c:\Users\<me>\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher 54602 -- TestMarlinOrder.py 99698
```
ERROR: c:\Program: The term 'c:\Program' is not recognized as a name of a cmdlet, function, script file, or executable program.

**Comment by eleanorjboyd** [comment]
seeing that without parameters we add quotes to the executable which fixes it since the executable has a space in it; I think this is the same problem [here which I just fixed](https://github.com/microsoft/vscode-python-debugger/commit/9db85ed7895f0559fb4d1ff59aa11ee0d21b3a7e). Closing, lmk if you still see the issue on the newest version of the extension
