### ISSUE TITLE
Timed out waiting for launcher to connect

### ISSUE THREAD

**Issue by wabiloo** [microsoft/vscode-python-debugger#495]
_Also posted in https://github.com/microsoft/debugpy/issues/1713, as I'm not sure whether the issue is with debugpy or the VS Code extension_

## Environment data

- extension version: v2024.13.2024101501 (pre-release) (but same problem with v2024.12.0)
- debugpy version: 1.8.7 (I think, but that's after running `python3 -m pip install debugpy`, and may not be the version used by VS Code. Not sure how to get that one. 
- OS and version: MacOS 14.3 (23D56)
- Python version (& distribution if applicable, e.g. Anaconda): v3.12.6 (but same issue with v3.11.7)
- Using VS Code or Visual Studio: VS Code v1.94.2 (but same issue on v1.93.1)

## Actual behavior

I have a very simple script:
```
import sys

print(len(sys.argv))
print(sys.argv)
if len(sys.argv) < 3:
    print(
        "specify <sheet-name> <operation> where operation is 'create', 'insert', show' or 'delete'"
    )
    sys.exit(1)

print("argument list:", str(sys.argv))
sheetname = sys.argv[1]
operation = sys.argv[2]
```

I launch it from the following launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python Debugger: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}
```

And I get the dreaded error message "Timed out waiting for the launcher to connect"

Strangely, I'm on v1.94.2 (something that was meant to have fixed a similar issue found by others and reported in https://github.com/microsoft/debugpy/issues/1677) and have been for at least a week, and everything was working fine, until suddenly in the middle of the afternoon last Friday, it stopped working... I had not changed anything to my settings or environment.
- Restarted the computer - no change
- I downgraded to VS Code v1.93.1 - no change
- Changed the version of python - no change

Logs attached
[debugger.vscode_62aa6d5d-f757-4cfc-a67f-52d139dcd71a.log](https://github.com/user-attachments/files/17542988/debugger.vscode_62aa6d5d-f757-4cfc-a67f-52d139dcd71a.log)
[debugpy.adapter-93288.log](https://github.com/user-attachments/files/17542987/debugpy.adapter-93288.log)

## Expected  behavior

Ability to run and debug Python code in VS Code

**Comment by karthiknadig** [comment]
This should be looked at in `debugpy`. Thanks for filing it there. I will close this.
