### ISSUE TITLE
Breakpoint and Step Over with multithreading

### ISSUE THREAD

**Issue by pub-pub** [microsoft/vscode-python-debugger#515]
there's an issue with debugging python code that utilizes multithreading.
i set a breakpoint, start debugging, execution pauses as expected, but when i press 'Step Over' (F10) debugger does not go to the next expression (line) in the current thread, but jumps to some random locations in other running threads, and i have to 'Step Over' again and again until i return to my current thread.

'Step Over' feature must be limited the current (paused) thread.

the same issue was reported for Visual Studio a couple of years ago https://developercommunity.visualstudio.com/t/make-the-debugger-stick-to-the-current-thread-inst/351390

**Comment by karthiknadig** [comment]
@pub-pub in `debugpy` the library there is a setting for this. Try adding this to the launch config: `"steppingResumesAllThreads": false`

**Comment by pub-pub** [comment]
> [@pub-pub](https://github.com/pub-pub) in `debugpy` the library there is a setting for this. Try adding this to the launch config: `"steppingResumesAllThreads": false`

thanks a lot, @karthiknadig 
it's working great

but i had to hardcode `False` into `pydevd_process_net_command_json.py` because i don't know where exactly i should put  `"steppingResumesAllThreads": false` in `launch.json`. can you, please, explain it to me?

and one more thing: maybe there's also a parameter that keeps me Stepping Over inside my thread without pausing all other threads?

**Comment by karthiknadig** [comment]
> maybe there's also a parameter that keeps me Stepping Over inside my thread without pausing all other threads?

@pub-pub debugpy has lot more control over this, but I am not sure if there is a stop only current option yet. This might be a feature request on debugpy. You can ask for it here https://github.com/microsoft/debugpy

**Comment by karthiknadig** [comment]
> but i had to hardcode `False` into `pydevd_process_net_command_json.py` because i don't know where exactly i should put  `"steppingResumesAllThreads": false` in `launch.json`. can you, please, explain it to me?

```
       {
            "name": "Python Debugger: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "steppingResumesAllThreads": false
        }
```

Even though it has the yellow line it should work.

**Comment by maor-outrival** [comment]
@karthiknadig the same thing happens in a subprocess and using "steppingResumesAllThreads": false doesn't work. Any suggestions there?

**Comment by rchiodo** [comment]
This should have been fixed. It was a bug in debugpy in 3.12 and above. The jumping between threads when stepping that is.

**Comment by maor-outrival** [comment]
@karthiknadig You are correct that it's a separate debugger but that behavior is not what is expected even from a separate debugger. 

I finally figured it out for a subprocess. It is a bug with the current version in debugpy, other users reported it as well. 
Downgrading to 2024.10.0 solved the issue.

**Comment by rchiodo** [comment]
>  It is a bug with the current version in debugpy, other users reported it as well. Downgrading to 2024.10.0 solved the issue.

Which bug? This should be fixed in our latest bits.
