### ISSUE TITLE
Can't install release version of 'ms-python.debugpy' extension because it has no release version

### ISSUE THREAD

**Issue by sunil-enable** [microsoft/vscode-python-debugger#76]
When trying to install the debugpy extension, I am prompted with the following error:

<img width="1118" alt="Screenshot 2023-08-11 at 11 59 56 AM" src="https://github.com/microsoft/vscode-python-debugger/assets/136069159/200b8ceb-6565-483a-bd1e-38b2aa313a65">

Is this expected behaviour? I can install pre-release version from dropdown

**Comment by karthiknadig** [comment]
Yes. This extension is still in preview.
