### ISSUE TITLE
Cant figure out why flask click cli command is failing to run

### ISSUE THREAD

**Issue by yawhide** [microsoft/vscode-python-debugger#82]
Howdy,

I have a flask application and am using [flask click custom commands](https://flask.palletsprojects.com/en/2.3.x/cli/#custom-commands). 

When I run my debugpy, i get the prompt to add cli arguments which I do. I then can see those cli arguments in the vscode terminal. But my program runs and then just exits. I put a breakpoint in the first line of the method where you define the custom command and it never hits it.

I opened the debugpy output and there isnt anything helpful there.
```
2023-09-03 18:52:50.522 [info] DAP Server launched with command: /Users/hello/flask-server/.venv/bin/python /Users/hello/.vscode/extensions/ms-python.debugpy-2023.3.12121004/bundled/libs/debugpy/adapter
```

Here is the terminal logs
```
cd /Users/hello/flask-server ; /usr/bin/env /Users/hello/.venv/bin/python /Users/hello/.vscode/extensions/ms-python.debugpy-2023.3.12121004/bundled/libs/debugpy/adapter/../../debugpy/launcher 51808 -- /Users/hello/flask-server/test-command.py -u 1
```

Here is my launch config (which looks very similar to my other launch configs):
```
{
      "name": "Debugpy: Current File with Arguments",
      "type": "debugpy",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal",
      "envFile": "${workspaceFolder}/.env",
      "env": {
        "FLASK_ENV": "development"
      },
      "args": "${command:pickArgs}",
      "justMyCode": false
    },
```

Any idea how to debug why things arent working?

**Comment by paulacamargo25** [comment]
Hi @yawhide thanks for your issue report, this configuration is only to run a simple python file with arguments not a Flask appication. If you want to run a flask application with args, you can try with the `Debugpy: Flask` configuration, and then just add the `"args": "${command:pickArgs}"`. Let me know if that works for you :D

**Comment by yawhide** [comment]
> Hi @yawhide thanks for your issue report, this configuration is only to run a simple python file with arguments not a Flask appication. If you want to run a flask application with args, you can try with the `Debugpy: Flask` configuration, and then just add the `"args": "${command:pickArgs}"`. Let me know if that works for you :D

thanks for responding.

whe ni make a new configuration using `click debugpy -> click flask`, i see this as the configuration added:

```
{
      "name": "Debugpy: Flask",
      "type": "debugpy",
      "request": "launch",
      "module": "flask",
      "env": { "FLASK_APP": "wsgi.py", "FLASK_DEBUG": "1" },
      "args": ["run", "--no-debugger", "--no-reload"],
      "jinja": true,
      "justMyCode": true
    },
```

I then try to run this, i see the prompt to add the cli args which I add and then nothing happens (no command is run in the terminal inside vscode).

I then editted the configuration above to add command:pickArgs:
```
{
      "name": "Debugpy: Flask",
      "type": "debugpy",
      "request": "launch",
      "module": "flask",
      "env": { "FLASK_APP": "wsgi.py", "FLASK_DEBUG": "1" },
      "args": "${command:pickArgs}",
      "jinja": true,
      "justMyCode": false
    },
```

Again, when I now try to debug, I add the cli args and then nothing happens. No command is run in the terminal.

When I debug my flask app, i see a command being run in the terminal:
```
/usr/bin/env /Users/hello/.venv/bin/python /U
sers/hello/.vscode/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 52432 -- -m flask run --no-debugger
```

my flask configuration:
```
{
      "name": "Python: Flask",
      "type": "python",
      "request": "launch",
      "module": "flask",
      "envFile": "${workspaceFolder}/.env",
      "env": {
        "FLASK_ENV": "development"
      },
      "args": ["run", "--no-debugger"],
      "jinja": true,
      "justMyCode": false
    },
```

It seems debugpy is just not running? or doesnt like my cli args? something must be preventing from debugpy from running after I pick the cli args?

i tried many versions of cli args:
* flask validate-script -u 187
* -u 187
* validate-script -u 187

if I were to run the cli tool on the terminal normally, i would run `flask validate-script -u 187`

**Comment by paulacamargo25** [comment]
H @yawhide the default config should run without any prompt, make sure that you are running the right one, if the error persist, could you send me the Python Debugger(debugpy) logs?
