### ISSUE TITLE
TPI: Test global configuration for justMyCode

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode-python-debugger#94]
Refs: https://github.com/microsoft/vscode-python-debugger/issues/83
- [x] macOS @connor4312  
- [x] linux @dbaeumer 
- [x] windows @karrtikr  

Complexity: 2

Author: @paulacamargo25 

---

Prerequisites:
- Install python version >= 3.7
- Install the [`debugpy`](https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy&ssr=false) extension.

Part 1: Create right configuration
  1. Create a python file with a simple code using external package.
  2. Go to `Run and debug`, then `Create a launch.json file`
  3. Select Debugpy > Python File
  4. Make sure the configuration has been created correctly, that is, that the type is `debugpy`, the name.
 
Part 2: Debug with justMyCode using different values
  1.  By default the value of justMyCode is `True`.  Set a breakpoint in the line that use the external package and try to jump inside the function. Check that it is not possible and that a message about the configuration will be shown.
  2. Go to the settings and update the value to `False`. Follow the steps mentioned above and now it should allow you to jump to the external code.

Part 3: Test updating config in `launch.json`
   1.  You can also modified the value in the `launch.json`, just add "justMyCode": true` to your debug configuration.
   2.  Run the same file and make sure the value being used is the one in the `launch.json` file, not in the settings.

**Comment by dbaeumer** [comment]
@paulacamargo25 step 2 is misleading. When you create a launch.json a property `"justMyCode": true` which always wins over the setting. So you can't step into the code by changing the settings value. I recommend to update the description or IMO even better to not generate a launch.json with that property since it is the default anyways.

**Comment by karrtikr** [comment]
> Go to the settings and update the value to False.

It would be helpful if you specify the setting name here (`"debugpy.debugJustMyCode"`) as not everyone is aware of the setting,
