### ISSUE TITLE
Remove justMyCode default values in debug configuration

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-python-debugger#96]
https://github.com/microsoft/vscode-python-debugger/issues/94

See screen cast. I can't step into the tempfile library.

![Image](https://github.com/microsoft/vscode-python-debugger/assets/1931590/2f89497e-fe57-43ed-a610-73234614e364)

**Comment by dbaeumer** [comment]
IM we should not generate the property in the `launch.json` since `true` is the default anyways. This allows to override the default via the setting and gives final control in the `launch.json`

**Comment by DonJayamanne** [comment]
Perhaps I need to wati for a new Python ext release, tested now and no joy.
