### ISSUE TITLE
turning off "just my code" in settings does not apply

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-python-debugger#99]
Refs https://github.com/microsoft/vscode-python-debugger/issues/94

2. Set `"debugpy.debugJustMyCode": false,` in the workspace settings or user settings (don't specify any value for 'just my code' in the launch.json)
1. Use the requests package and have some line like `r = requests.get(url)`
3. Try to step into that line
4. It's skipped 🐛

**Comment by DonJayamanne** [comment]
Waiting for a new release of Python ext.
